In [1]:
import numpy as np
import scipy as sp

# Matemáticas para aprendizaje automático

## Álgebra lineal

### Repaso de cálculo matricial

**David Ramírez**

Departamento de Teoría de la Señal y Comunicaciones

**Universidad Carlos III de Madrid**

<img src='./figures/UC3M.svg' width=300 />

### Contenidos

- Operaciones básicas
- Traza y determinante
- Inversa y pseudo-inversa de Moore-Penrose


## Operaciones básicas

#### ¿Qué es una matriz?

Una matriz de tamaño $n \times m$ es un *array* de números:

\begin{equation}
{\mathbf A} = \begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1m} \\
a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nm} 
\end{bmatrix}
\end{equation}

In [2]:
# Matrices de ejemplo
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A)

# Elementos de la matriz (ATENCIÓN: Python empieza a contar en 0)
print(A[0,0])

# Filas de la matriz
print(A[1,:])

# Columnas de la matriz
print(A[:,2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
1
[4 5 6]
[ 3  6  9 12]


#### Suma/resta de matrices

La suma de dos matrices de igual tamaño es

\begin{equation}
{\mathbf C} = {\mathbf A} + {\mathbf B} = \begin{bmatrix}
c_{11} & c_{12} & \cdots & c_{1m} \\
c_{21} & c_{22} & \cdots & c_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
c_{n1} & c_{n2} & \cdots & c_{nm} 
\end{bmatrix}
\end{equation}

donde $c_{ij} = a_{ij} + b_{ij}$

In [3]:
# Matrices de ejemplo
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[12,11,10],[9,8,7],[6,5,4],[3,2,1]])

# Suma de matrices
C = A + B
print(C)

[[13 13 13]
 [13 13 13]
 [13 13 13]
 [13 13 13]]


#### Producto escalar de dos vectores

El producto escalar de dos vectores de la misma dimensión da como resultado un escalar. Concretamente es

\begin{equation}
c = {\mathbf a}^T \, {\mathbf b} = \begin{bmatrix}
a_{1} & a_{2} & \cdots & a_{n}
\end{bmatrix}
\begin{bmatrix}
b_{1} \\ b_{2} \\ \vdots \\ b_{n} \\
\end{bmatrix} = \sum_{i = 1}^{n} a_i b_i
\end{equation}

Por defecto, los vectores serán vectores columna.

#### Producto externo de dos vectores

El producto externo de dos vectores da como resultado una matriz (de rango 1). Concretamente es

\begin{equation}
{\mathbf C} = {\mathbf a} {\mathbf b}^T  = \begin{bmatrix}
a_{1} b_1 & a_{1} b_2 & \cdots & a_{1} b_m \\
a_{2} b_1 & a_{2} b_2 & \cdots & a_{2} b_m \\
\vdots & \vdots & \ddots & \vdots \\
a_{n} b_1 & a_{n} b_2 & \cdots & a_{n} b_m \\
\end{bmatrix}
\end{equation}

donde ${\mathbf a} = [a_{1} \ a_{2} \ \cdots \ a_{n}]^T$ es un vector $n$-dimensional, ${\mathbf b} = [b_{1} \ b_{2} \ \cdots \ b_{m}]^T$ es un vector $m$-dimensional y ${\mathbf C}$ es una matriz de dimensiones $n \times m$

In [4]:
# Vectores de ejemplo
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]);a.shape = (12,1)
b = np.array([12,11,10,9,8,7,6,5,4,3,2,1]);b.shape = (12,1)

# Producto escalar de vectores
c = a.T @ b
print(c)

# Producto externo de vectores
C = a @ b.T
print(C)

[[364]]
[[ 12  11  10   9   8   7   6   5   4   3   2   1]
 [ 24  22  20  18  16  14  12  10   8   6   4   2]
 [ 36  33  30  27  24  21  18  15  12   9   6   3]
 [ 48  44  40  36  32  28  24  20  16  12   8   4]
 [ 60  55  50  45  40  35  30  25  20  15  10   5]
 [ 72  66  60  54  48  42  36  30  24  18  12   6]
 [ 84  77  70  63  56  49  42  35  28  21  14   7]
 [ 96  88  80  72  64  56  48  40  32  24  16   8]
 [108  99  90  81  72  63  54  45  36  27  18   9]
 [120 110 100  90  80  70  60  50  40  30  20  10]
 [132 121 110  99  88  77  66  55  44  33  22  11]
 [144 132 120 108  96  84  72  60  48  36  24  12]]


#### Producto de matriz por escalar

El producto de un escalar $c$ por una matriz ${\mathbf A}$ de tamaño $n \times m$ es

\begin{equation}
{\mathbf B} = c \, {\mathbf A} = \begin{bmatrix}
b_{11} & b_{12} & \cdots & b_{1m} \\
b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
b_{n1} & b_{n2} & \cdots & b_{nm} 
\end{bmatrix}
\end{equation}

donde 

\begin{equation}
b_{ij} = c \, a_{ij}
\end{equation}

In [5]:
# Matriz y escalar de ejemplo
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c = 4

# Producto de matriz por escalar
B = c*A
print(B)

[[ 4  8 12]
 [16 20 24]
 [28 32 36]
 [40 44 48]]


#### Producto de matrices

El producto de dos matrices de tamaños compatibles (${\mathbf A}$ es $n \times p$ y ${\mathbf B}$ es $p \times m$) es

\begin{equation}
{\mathbf C} = {\mathbf A} {\mathbf B} = \begin{bmatrix}
c_{11} & c_{12} & \cdots & c_{1m} \\
c_{21} & c_{22} & \cdots & c_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
c_{n1} & c_{n2} & \cdots & c_{nm} 
\end{bmatrix}
\end{equation}

donde 

\begin{equation}
c_{ij} = \sum_{l = 1}^{p} a_{il} b_{lj}
\end{equation}

Esta es la definición clásica, pero puede ser más interesante considerar las filas de ${\mathbf A}$ y las columna de ${\mathbf B}$, esto es

\begin{equation}
{\mathbf C} = {\mathbf A} {\mathbf B} =
\left[
\begin{array}{ccccc}
 &  & {\mathbf a}_1^T &  & \\
 \hline
 &  & {\mathbf a}_2^T &  & \\
 \hline
  &  & \vdots &  & \\
 \hline
  &  & {\mathbf a}_n^T &  & \\
\end{array}
\right]
\left[
\begin{array}{c|c|c|c}
 &  &  &  \\
&  &  &  \\
{\mathbf b}_1 & {\mathbf b}_2 & \cdots & {\mathbf b}_m \\
&  &  &  \\
&  &  &  
\end{array}
\right]
=\begin{bmatrix}
c_{11} & c_{12} & \cdots & c_{1m} \\
c_{21} & c_{22} & \cdots & c_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
c_{n1} & c_{n2} & \cdots & c_{nm} 
\end{bmatrix}
\end{equation}

donde 

\begin{equation}
c_{ij} = {\mathbf a}_i^T {\mathbf b}_j
\end{equation}


In [6]:
# Matrices de ejemplo
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[12,11,10],[9,8,7],[6,5,4]])

# Producto de matrices
C = A @ B
print(C)

# Producto de matrices (versión alternativa)
C = np.dot(A,B)
print(C)

[[ 48  42  36]
 [129 114  99]
 [210 186 162]
 [291 258 225]]
[[ 48  42  36]
 [129 114  99]
 [210 186 162]
 [291 258 225]]


En el caso de que ${\mathbf B}$ sea el vector ${\mathbf b}$ de tamaño $p \times 1$, el producto es

\begin{equation}
{\mathbf c} = {\mathbf A} {\mathbf b} = \begin{bmatrix}
c_{1} \\
c_{2} \\
\vdots \\
c_{n}
\end{bmatrix} = \sum_{l = 1}^{p} {\mathbf a}_l b_l
\end{equation}

donde ${\mathbf a}_l$ es la $l$-ésima columna de ${\mathbf A}$. Esta ecuación se puede representar esquemáticamente como

\begin{equation}
\left[
\begin{array}{c}
\\
\\
{\mathbf c} \\
\\
\\
\end{array}
\right] = 
\left[
\begin{array}{c|c|c|c}
 &  &  &  \\
&  &  &  \\
{\mathbf a}_1 & {\mathbf a}_2 & \cdots & {\mathbf a}_p \\
&  &  &  \\
&  &  &  
\end{array}
\right]
\begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots \\
b_{p}
\end{bmatrix} =
b_1 \left[\begin{array}{c}
\\
\\
{\mathbf a}_1 \\
\\
\\
\end{array}
\right]
+ \cdots +
b_p \left[\begin{array}{c}
\\
\\
{\mathbf a}_p \\
\\
\\
\end{array}
\right]
\end{equation}

El producto matriz-vector tiene una interesante interpretación geométrica que se estudiará en más detalle en la sección de "Espacios vectoriales"

<img 
    style="display: block; 
           margin-left: auto;
           margin-right: auto;
           width: 40%;"
    src='./figures/span.svg'/>
</img>

#### Producto de Hadamard de matrices

El producto de Hadamard (o elemento a elemento) de dos matrices del mismo tamaño es

\begin{equation}
{\mathbf C} = {\mathbf A} \odot {\mathbf B} = \begin{bmatrix}
c_{11} & c_{12} & \cdots & c_{1m} \\
c_{21} & c_{22} & \cdots & c_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
c_{n1} & c_{n2} & \cdots & c_{nm} 
\end{bmatrix}
\end{equation}

donde 

\begin{equation}
c_{ij} = a_{ij} b_{ij}
\end{equation}

In [7]:
# Matrices de ejemplo
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[12,11,10],[9,8,7],[6,5,4],[3,2,1]])

# Producto de Hadamard de matrices: Como se puede ver es el producto convencional de Python
C = A * B
print(C)

[[12 22 30]
 [36 40 42]
 [42 40 36]
 [30 22 12]]


#### Producto de Kronecker de matrices

El producto de Kronecker de dos matrices es

\begin{equation}
{\mathbf C} = {\mathbf A} \otimes {\mathbf B} = \begin{bmatrix}
a_{11} {\mathbf B} & a_{12} {\mathbf B} & \cdots & a_{1m} {\mathbf B} \\
a_{21} {\mathbf B} & a_{22} {\mathbf B} & \cdots & a_{2m} {\mathbf B} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} {\mathbf B} & a_{n2} {\mathbf B} & \cdots & a_{nm} {\mathbf B}
\end{bmatrix}
\end{equation}

donde ${\mathbf A}$ es una matriz $n \times m$ y ${\mathbf B}$ es una matriz $p \times q$. Es decir, ${\mathbf C}$ es una matriz $np \times mq$

In [8]:
# Matrices de ejemplo
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[12,11,10],[9,8,7],[6,5,4],[3,2,1]])

# Producto de Kronecker
C = np.kron(A,B)
print(C)
print(C.shape)

[[ 12  11  10  24  22  20  36  33  30]
 [  9   8   7  18  16  14  27  24  21]
 [  6   5   4  12  10   8  18  15  12]
 [  3   2   1   6   4   2   9   6   3]
 [ 48  44  40  60  55  50  72  66  60]
 [ 36  32  28  45  40  35  54  48  42]
 [ 24  20  16  30  25  20  36  30  24]
 [ 12   8   4  15  10   5  18  12   6]
 [ 84  77  70  96  88  80 108  99  90]
 [ 63  56  49  72  64  56  81  72  63]
 [ 42  35  28  48  40  32  54  45  36]
 [ 21  14   7  24  16   8  27  18   9]]
(12, 9)


#### Matriz traspuesta y Hermítica traspuesta

La traspuesta de la matriz ${\mathbf A}$ es la matriz

\begin{equation}
{\mathbf A}^T = \begin{bmatrix}
a_{11} & a_{21} & \cdots & a_{n1} \\
a_{12} & a_{22} & \cdots & a_{n2} \\
\vdots & \vdots & \ddots & \vdots \\
a_{1m} & a_{2m} & \cdots & a_{nm} 
\end{bmatrix}
\end{equation}

de dimensiones $m \times n$. La Hermítica de la matriz ${\mathbf A}$ es la matriz

\begin{equation}
{\mathbf A}^H = \begin{bmatrix}
a_{11}^* & a_{21}^* & \cdots & a_{n1}^* \\
a_{12}^* & a_{22}^* & \cdots & a_{n2}^* \\
\vdots & \vdots & \ddots & \vdots \\
a_{1m}^* & a_{2m}^* & \cdots & a_{nm}^* 
\end{bmatrix}
\end{equation}

de dimensiones $m \times n$. Para matrices reales ${\mathbf A}^H = {\mathbf A}^T$

##### Propiedades:

1. $({\mathbf A} + {\mathbf B})^H = {\mathbf A}^H + {\mathbf B}^H$
2. $({\mathbf A} {\mathbf B})^H = {\mathbf B}^H {\mathbf A}^H$

##### Matrices simétricas y Hermíticas

Diremos que ${\mathbf A}$ es una **matriz simétrica** si ${\mathbf A}^T = {\mathbf A}$ y diremos que es una **matriz Hermítica** si ${\mathbf A}^H = {\mathbf A}$. A partir de aquí, consideraremos siempre matrices reales

In [9]:
# Matrices de ejemplo
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[12,11,10],[9,8,7],[6,5,4],[3,2,1]])

# Traspuesta de A
A_T = np.transpose(A)
print(A_T)
print(A.T)

# Suma de traspuestas
C = A + B

print(C.T)
print(A.T + B.T)

# Producto de traspuestas
B = np.array([[12,11,10],[9,8,7],[6,5,4]])
C = A @ B

print(C.T)
print(B.T @ A.T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[13 13 13 13]
 [13 13 13 13]
 [13 13 13 13]]
[[13 13 13 13]
 [13 13 13 13]
 [13 13 13 13]]
[[ 48 129 210 291]
 [ 42 114 186 258]
 [ 36  99 162 225]]
[[ 48 129 210 291]
 [ 42 114 186 258]
 [ 36  99 162 225]]


## Traza de una matriz

La traza de una matriz cuadrada de tamaño $n \times n$ es

\begin{equation}
\operatorname{tr}({\mathbf A}) = \sum_{i = 1}^{n} a_{ii}
\end{equation}

##### Propiedades:

1. $\operatorname{tr}({\mathbf A}^T) = \operatorname{tr}({\mathbf A})$
2. $\operatorname{tr}(c {\mathbf A}) = c \operatorname{tr}({\mathbf A})$
3. $\operatorname{tr}({\mathbf A} + {\mathbf B}) = \operatorname{tr}({\mathbf A}) + \operatorname{tr}({\mathbf B})$
4. $\operatorname{tr}({\mathbf A} {\mathbf B} {\mathbf C}) = \operatorname{tr}({\mathbf C} {\mathbf A} {\mathbf B}) = \operatorname{tr}({\mathbf B} {\mathbf C} {\mathbf A})$

In [10]:
# Matrices de ejemplo
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[12,11,10],[9,8,7],[6,5,4]])
C = np.array([[15,16,17],[18,19,20],[21,22,23]])
c = 4

print(np.trace(A))

# Traza de traspuesta
print(np.trace(A.T))

# Traza de producto por escalar
print(np.trace(c*A))
print(c*np.trace(A))

# Propiedad cíclica
print(np.trace(A @ B @ C))
print(np.trace(C @ A @ B))
print(np.trace(B @ C @ A))

15
15
60
60
19656
19656
19656


## Determinante de una matriz

El determinante de una matriz cuadrada de tamaño $n \times n$ es

\begin{equation}
\operatorname{det}({\mathbf A}) = \sum_{{\boldsymbol \sigma}} (-1)^{N({\boldsymbol \sigma})} \prod_{i = 1}^{n} a_{i \sigma_i}
\end{equation}

donde ${\boldsymbol \sigma}$ es una permutación de $1, \ldots, n$, $\sum_{{\boldsymbol \sigma}}$ denota la suma sobre la $n!$ permutaciones de $1, \ldots, n$ y $N({\boldsymbol \sigma})$ es el número de inversiones de la permutación ${\boldsymbol \sigma}$.

##### Relación con el volumen: $|\operatorname{det}({\mathbf A})|$ es el volumen del paralelepípedo formado por las columnas de ${\mathbf A}$

##### Propiedades:

1. Si la fila (o columna) $i$-ésima se multiplica por $c$, el determinante también. Por lo tanto, $\operatorname{det}(c {\mathbf A}) = c^n \operatorname{det}({\mathbf A})$
2. Intercambiar dos filas (o columnas) cambia el signo del determinante
3. Si dos filas (o columnas) de ${\mathbf A}$ son idénticas, entonces $\operatorname{det}({\mathbf A}) = 0$
4. $\operatorname{det}({\mathbf A} {\mathbf B}) = \operatorname{det}({\mathbf B} {\mathbf A}) = \operatorname{det}({\mathbf A}) \operatorname{det}({\mathbf B})$ para matrices ${\mathbf A}$ y ${\mathbf B}$ de dimensiones $n \times n$

In [11]:
# Matrices de ejemplo
A = np.array([[1,3,7],[4,2,9],[5,8,6]])
B = np.array([[12,5,10],[6,8,7],[9,11,4]])
c = 4

print(np.linalg.det(A))

# Determinante de producto por escalar
A_tilde = A.copy()
A_tilde[:,1] *= c

print(np.linalg.det(A_tilde))
print(c*np.linalg.det(A))

n = A.shape[0]
print(np.linalg.det(c*A))
print(c**n*np.linalg.det(A))

# Determinante de intercambio de filas/columnas
A_tilde = A.copy()
A_tilde[:, [0, 2]] = A_tilde[:, [2, 0]]

print(np.linalg.det(A_tilde))

# Determinante de matrix con columnas idénticas
A_tilde = A.copy()
A_tilde[:, 0] = A_tilde[:, 2]

print(np.linalg.det(A_tilde))

# Determinante del producto
print(np.linalg.det(A @ B))
print(np.linalg.det(A) * np.linalg.det(B))

156.99999999999994
627.9999999999999
627.9999999999998
10048.000000000002
10047.999999999996
-157.00000000000009
5.32907051820075e-14
-63585.00000000001
-63584.99999999995


## Inversa de una matriz

Como no es posible dividir matrices, se define la matriz inversa para conseguir el mismo objetivo. Concretamente, la matriz inversa de una matriz cuadrada ${\mathbf A}$, que se denota como ${\mathbf A}^{-1}$, es una matriz que cumple

\begin{equation}
{\mathbf A} {\mathbf A}^{-1} = {\mathbf A}^{-1} {\mathbf A} = {\mathbf I}
\end{equation}

donde ${\mathbf I}$ es la matriz identidad

\begin{equation}
{\mathbf I} = \begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1
\end{bmatrix}
\end{equation}

Pero la inversa sólo existe para matrices regulares, o no singulares, es decir, para las que $\operatorname{det}({\mathbf A}) \neq 0$

##### Propiedades:

1. $\left({\mathbf A}^{-1}\right)^T = \left({\mathbf A}^T\right)^{-1}$
2. Si ${\mathbf A}$ y ${\mathbf B}$ son regulares $\left({\mathbf A} {\mathbf B}\right)^{-1} = {\mathbf B}^{-1} {\mathbf A}^{-1}$
3. $\operatorname{det}({\mathbf A}^{-1}) = 1/\operatorname{det}({\mathbf A})$

In [12]:
# Matrices de ejemplo
A = np.array([[1,3,7],[4,2,9],[5,8,6]])
B = np.array([[12,5,10],[6,8,7],[9,11,4]])

# Inversa de A
A_inv = np.linalg.inv(A)
print(A @ A_inv)
print(A_inv @ A)

# Inversa de la traspuesta/hermítica
print(np.linalg.inv(A.T))
print(np.linalg.inv(A).T)

# Inversa de productos
C = A @ B
print(np.linalg.inv(C))
print(np.linalg.inv(B) @ np.linalg.inv(A))

[[ 1.00000000e+00  4.16333634e-17 -2.77555756e-17]
 [ 5.55111512e-17  1.00000000e+00 -2.77555756e-17]
 [ 1.11022302e-16  8.32667268e-17  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  2.77555756e-16]
 [-1.38777878e-17  1.00000000e+00  2.77555756e-17]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00]]
[[-0.38216561  0.13375796  0.14012739]
 [ 0.24203822 -0.18471338  0.04458599]
 [ 0.08280255  0.12101911 -0.06369427]]
[[-0.38216561  0.13375796  0.14012739]
 [ 0.24203822 -0.18471338  0.04458599]
 [ 0.08280255  0.12101911 -0.06369427]]
[[-0.05661713  0.07289455 -0.02476999]
 [ 0.05897617 -0.03982071  0.00080208]
 [ 0.0002359  -0.04335928  0.03760321]]
[[-0.05661713  0.07289455 -0.02476999]
 [ 0.05897617 -0.03982071  0.00080208]
 [ 0.0002359  -0.04335928  0.03760321]]


## Pseudo-inversa de Moore-Penrose

En algunos casos, no existe la inversa de una matriz, ya que esta puede ser singular o no ser cuadrada. Para estas matrices, se define la matriz pseudo-inversa. Para una matriz ${\mathbf A}$ de tamaño $n \times m$, se define su matriz pseudo-inversa, ${\mathbf A}^{\#}$, a la matriz que cumple

1. ${\mathbf A}^{\#} {\mathbf A} = \left({\mathbf A}^{\#} {\mathbf A}\right)^T$
2. ${\mathbf A} {\mathbf A}^{\#} = \left({\mathbf A} {\mathbf A}^{\#}\right)^T$
3. ${\mathbf A}^{\#} {\mathbf A} {\mathbf A}^{\#} = {\mathbf A}^{\#}$
4. ${\mathbf A} {\mathbf A}^{\#} {\mathbf A} = {\mathbf A}$

En la sección de descomposiciones matriciales, se verá cómo es el cálculo de la pseudo-inversa. Por el momento, podemos usar la función de Numpy

In [13]:
# Matrices de ejemplo
A = np.array([[1,3,7],[4,2,9],[5,8,6], [12,10,13]])

# Pseudo-inversa de A
A_pinv = np.linalg.pinv(A)

# Condición 1
print(A_pinv @ A)
print(np.transpose(A_pinv @ A))

# Condición 2
print(A @ A_pinv)
print(np.transpose(A @ A_pinv))

# Condición 3
print(A_pinv @ A @ A_pinv)
print(A_pinv)

# Condición 4
print(A @ A_pinv @ A)
print(A)

[[ 1.00000000e+00  3.88578059e-16  4.16333634e-16]
 [-8.32667268e-17  1.00000000e+00 -2.56739074e-16]
 [-2.22044605e-16 -3.33066907e-16  1.00000000e+00]]
[[ 1.00000000e+00 -8.32667268e-17 -2.22044605e-16]
 [ 3.88578059e-16  1.00000000e+00 -3.33066907e-16]
 [ 4.16333634e-16 -2.56739074e-16  1.00000000e+00]]
[[ 0.73243748  0.30698022  0.25800672 -0.18753266]
 [ 0.30698022  0.64779502 -0.29601664  0.21516024]
 [ 0.25800672 -0.29601664  0.75120781  0.18083507]
 [-0.18753266  0.21516024  0.18083507  0.8685597 ]]
[[ 0.73243748  0.30698022  0.25800672 -0.18753266]
 [ 0.30698022  0.64779502 -0.29601664  0.21516024]
 [ 0.25800672 -0.29601664  0.75120781  0.18083507]
 [-0.18753266  0.21516024  0.18083507  0.8685597 ]]
[[-0.18424785  0.01496294 -0.10804671  0.13871914]
 [ 0.07248973 -0.11441903  0.18009918 -0.04294246]
 [ 0.09988802  0.09075348 -0.02489202 -0.02820349]]
[[-0.18424785  0.01496294 -0.10804671  0.13871914]
 [ 0.07248973 -0.11441903  0.18009918 -0.04294246]
 [ 0.09988802  0.09075348 