In [1]:
import numpy as np
import scipy as sp

# Matemáticas para aprendizaje automático

## Álgebra lineal

### Producto escalar y normas vectoriales y matriciales

**David Ramírez**

Departamento de Teoría de la Señal y Comunicaciones

**Universidad Carlos III de Madrid**

<img src='./figures/UC3M.svg' width=300 />



### Contenidos

- Producto escalar y normas vectoriales
- Normas matriciales


## Producto escalar y normas vectoriales

#### Producto escalar de dos vectores

Recordemos la definición del producto escalar

\begin{equation}
c = {\mathbf a}^T \, {\mathbf b} = \begin{bmatrix}
a_{1} & a_{2} & \cdots & a_{n}
\end{bmatrix}
\begin{bmatrix}
b_{1} \\ b_{2} \\ \vdots \\ b_{n} \\
\end{bmatrix} = \sum_{i = 1}^{n} a_i b_i
\end{equation}

##### Propiedades:

1. $({\mathbf a}_1 + {\mathbf a}_2)^T {\mathbf b} = {\mathbf a}_1^T {\mathbf b} + {\mathbf a}_2^T {\mathbf b}$
2. ${\mathbf a}^T ({\mathbf b}_1 + {\mathbf b}_2) = {\mathbf a}^T {\mathbf b}_1 + {\mathbf a}^T {\mathbf b}_2$
3. $(c {\mathbf a})^T (d {\mathbf b}) = c d \, {\mathbf a}^T \, {\mathbf b}$

#### Norma $\ell_2$ de un vector

El producto escalar también nos permite definir la longitud Euclídea (o norma "clásica") del vector. Concretamente, la norma $\ell_2$ del vector ${\mathbf a}$ viene dada por

\begin{equation}
\|{\mathbf a}\|_2 = \sqrt{{\mathbf a}^T \, {\mathbf a}} = \sqrt{\sum_{i = 1}^{n} a_i^2}
\end{equation}

In [2]:
# Vector de ejemplo
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]);a.shape = (12,1)

# Norma ell_2 de a
print(a.T @ a)

print(np.linalg.norm(a)**2)

[[650]]
650.0


#### Interpretación geométrica del producto escalar

El producto escalar admite la definicion alternativa

\begin{equation}
{\mathbf a}^T \, {\mathbf b} = \|{\mathbf a}\|_2 \|{\mathbf b}\|_2 \cos(\theta)
\end{equation}

donde $\theta$ es el ángulo que forman los vectores ${\mathbf a}$ y ${\mathbf b}$. Suponiendo que $\|{\mathbf a}\|_2 = 1$, ${\mathbf a}^T \, {\mathbf b}$ mide la longitud de la proyección de ${\mathbf b}$ sobre ${\mathbf a}$, como muestra la siguiente figura

<img 
    style="display: block; 
           margin-left: auto;
           margin-right: auto;
           width: 30%;"
    src='./figures/scalar_product.svg'/>
</img>

#### Vectores ortogonales

El ángulo $\theta$ permite introducir con el producto escalar la definición de vectores ortogonales (o perpendiculares). Concretamente, dos vectores ortogonales formarán un ángulo $\theta = 90$ grados y, por lo tanto, diremos que dos vectores son ortogonales si su producto escalar es 

\begin{equation}
{\mathbf a}^T \, {\mathbf b} = 0
\end{equation}

#### Matrices ortogonales

Se dice que una matriz cuadrada ${\mathbf U}$ es una matriz ortogonal si sus columnas son ortogonales y de norma unidad. Es decir, si definimos 

\begin{equation}
{\mathbf U} = 
\left[
\begin{array}{c|c|c|c}
 &  &  &  \\
&  &  &  \\
{\mathbf u} _1 & {\mathbf u} _2 & \cdots & {\mathbf u} _n \\
&  &  &  \\
&  &  &  
\end{array}
\right]
\end{equation}

se tiene que cumplir ${\mathbf u}_i^T {\mathbf u}_j = 0, i \neq j,$ y ${\mathbf u}_i^T {\mathbf u}_i = \|{\mathbf u}_i\|^2_2 = 1$. Estas condiciones se pueden reescribir de manera más compacta como

\begin{equation}
\left[
\begin{array}{ccccc}
 &  & {\mathbf u}_1^T &  & \\
 \hline
 &  & {\mathbf u}_2^T &  & \\
 \hline
  &  & \vdots &  & \\
 \hline
  &  & {\mathbf u}_n^T &  & \\
\end{array}
\right]
\left[
\begin{array}{c|c|c|c}
 &  &  &  \\
&  &  &  \\
{\mathbf u}_1 & {\mathbf u}_2 & \cdots & {\mathbf u}_n \\
&  &  &  \\
&  &  &  
\end{array}
\right] = 
\begin{bmatrix}
{\mathbf u}_1^T {\mathbf u}_1 & {\mathbf u}_1^T {\mathbf u}_2 & \cdots & {\mathbf u}_1^T {\mathbf u}_n \\
{\mathbf u}_2^T {\mathbf u}_1 & {\mathbf u}_2^T {\mathbf u}_2 & \cdots & {\mathbf u}_2^T {\mathbf u}_n \\
\vdots & \vdots & \ddots & \vdots \\
{\mathbf u}_n^T {\mathbf u}_1 & {\mathbf u}_n^T {\mathbf u}_2 & \cdots & {\mathbf u}_n^T {\mathbf u}_n
\end{bmatrix}
= \begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1
\end{bmatrix}
\end{equation}

o, de manera equivalente

\begin{equation}
{\mathbf U}^T {\mathbf U}  = {\mathbf I} 
\end{equation}

Es decir, para una matriz ortogonal ${\mathbf U}^{-1} = {\mathbf U}^T$. Finalmente, teniendo en cuenta esto último, tenemos la definición habitual de matriz ortogonal

\begin{equation}
{\mathbf U}^T {\mathbf U}  = {\mathbf U}  {\mathbf U}^T = {\mathbf I} 
\end{equation}

In [3]:
# Matriz de ejemplo: "ortogonalizamos" una matriz cualquiera
U = sp.linalg.orth(np.array([[2,1,3],[4,6,5],[7,8,9]]))
print(U)

# Condición de ortogonalidad
print(U.T @ U)
print(U @ U.T)

# Cálculo de la inversa
print(U.T)
print(np.linalg.inv(U))

[[-0.20776595  0.77968819 -0.5906942 ]
 [-0.51886325 -0.59976014 -0.60915408]
 [-0.82922508  0.17992804  0.52916128]]
[[ 1.00000000e+00 -1.23166265e-16 -9.01406607e-17]
 [-1.23166265e-16  1.00000000e+00 -1.76640966e-16]
 [-9.01406607e-17 -1.76640966e-16  1.00000000e+00]]
[[ 1.00000000e+00 -1.22842983e-16  1.26250696e-16]
 [-1.22842983e-16  1.00000000e+00  1.35244740e-16]
 [ 1.26250696e-16  1.35244740e-16  1.00000000e+00]]
[[-0.20776595 -0.51886325 -0.82922508]
 [ 0.77968819 -0.59976014  0.17992804]
 [-0.5906942  -0.60915408  0.52916128]]
[[-0.20776595 -0.51886325 -0.82922508]
 [ 0.77968819 -0.59976014  0.17992804]
 [-0.5906942  -0.60915408  0.52916128]]


##### *Slice* de una matriz ortogonal

Supongamos que tenemos un conjunto de $m$ vectores de tamaño $n$, con $m <n$, que son ortogonales y tienen norma unidad: ${\mathbf u} _i, i = 1, \ldots, m$. En este caso, la matriz

\begin{equation}
{\mathbf U}  = 
\left[
\begin{array}{c|c|c|c}
 &  &  &  \\
&  &  &  \\
{\mathbf u} _1 & {\mathbf u} _2 & \cdots & {\mathbf u} _m \\
&  &  &  \\
&  &  &  
\end{array}
\right]
\end{equation}

no es ortogonal por no ser cuadrada. Es decir, se cumple

\begin{equation}
{\mathbf U}^T {\mathbf U}  = {\mathbf I} 
\end{equation}

pero

\begin{equation}
{\mathbf U}  {\mathbf U}^T \neq {\mathbf I} 
\end{equation}

Por lo tanto, ${\mathbf U}^T \neq {\mathbf U} ^{-1}$.

In [4]:
# Matriz de ejemplo
U = sp.linalg.orth(np.array([[2,1],[4,6],[7,8]]))
print(U)

# Condición de ortogonalidad
print(U.T @ U)
print(U @ U.T)

[[-0.15740036  0.7530351 ]
 [-0.55261295 -0.60332967]
 [-0.81844002  0.262548  ]]
[[ 1.00000000e+00 -1.18612005e-16]
 [-1.18612005e-16  1.00000000e+00]]
[[ 0.59183673 -0.36734694  0.32653061]
 [-0.36734694  0.66938776  0.29387755]
 [ 0.32653061  0.29387755  0.73877551]]


#### Norma $\ell_p$ de un vector

La norma $\ell_p$ de un vector es la clase de normas más popular para vectores. En particular, toda norma debe cumplir

\begin{equation}
 \| {\mathbf a} \| \geq 0, \qquad \text{ y } \qquad \| {\mathbf a} \| = 0 \text{ sólo si } {\mathbf a} = {\boldsymbol 0}
\end{equation}
\begin{equation}
 \| {\mathbf a} + {\mathbf b} \| \leq \| {\mathbf a} \| + \| {\mathbf b} \|
\end{equation}
\begin{equation}
 \| c {\mathbf a} \| = |c| \| {\mathbf a} \|
\end{equation}

La norma $\ell_p$, con $p \geq 1$, se define como

\begin{equation}
 \| {\mathbf a} \|_p = \left(\sum_{i = 1}^{n} |a_i|^{p} \right)^{1/p}
\end{equation}

Hay unos casos importantes

\begin{equation}
 \| {\mathbf a} \|_1 = \sum_{i = 1}^{n} |a_i| \qquad \| {\mathbf a} \|_2 = \left(\sum_{i = 1}^{n} |a_i|^{2} \right)^{1/2} \qquad \| {\mathbf a} \|_{\infty} = \max_{1 \leq i \leq n} |a_i|
\end{equation}

y en la siguiente figura se muestran las bolas unitarias para las normas anteriores, junto con la de un valor de $p$ genérico

<img 
    style="display: block; 
           margin-left: auto;
           margin-right: auto;
           width: 50%;"
    src='./figures/norms_vectors.svg'/>
</img>

Es decir, las curvas en azul son todos los puntos ${\mathbf a}$ para los que $\|{\mathbf a}\|_p = 1$

In [5]:
# Vector de ejemplo
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]);a.shape = (12,1) # Forzamos que sea columna

# Normas ell_p de a (no todos los valores de p se admiten)
print(np.linalg.norm(a,ord=1))
print(np.linalg.norm(a,ord=2))
print(np.linalg.norm(a,ord=np.inf))

78.0
25.495097567963924
12.0


#### Norma $\ell_p$ ponderada

Definiendo una matriz diagonal ${\mathbf W}$, con valores en la diagonal positivos, la norma $\ell_p$ ponderada es

\begin{equation}
 \| {\mathbf a} \|_{{\mathbf W},p} = \| {\mathbf W} {\mathbf a} \|_{p} = \left(\sum_{i = 1}^{n} |w_i a_i|^{p} \right)^{1/p}
\end{equation}

Es posible generalizar la definición anterior a matrices no singulares arbitrarias, pero su interpretación geométrica se complica ya que en el caso de matrices diagonales consiste simplemente en "estirar" los ejes

## Normas matriciales

#### Normas elemento a elemento

La matriz ${\mathbf A}$ de dimensiones $m \times n$ se puede ver como un vector $mn$ dimensional y, por lo tanto, se puede calcular la norma para esta "vectorización de la matriz"

\begin{equation}
 \| {\mathbf A}  \|_{p} = \| \operatorname{vec}({\mathbf A} ) \|_{p}
\end{equation}

Una alternativa más elaborada es considerar que la matriz ${\mathbf A}$ es un conjunto de $n$ vectores de dimensión $m$. Para cada uno de los $n$ vectores podemos calcular su norma $\ell_p$ y estas $n$ normas las podemos reescribir como en vector de tamaño $n$

\begin{equation}
 {\mathbf b} = \begin{bmatrix} 
 \| {\mathbf a}_1 \|_p \\ \| {\mathbf a}_2 \|_p \\ \vdots \\ \| {\mathbf a}_n \|_p
 \end{bmatrix} 
\end{equation}

La norma $\ell_q$ de ${\mathbf b}$ sería la norma $\| {\mathbf A}  \|_{p,q}$, dada por

\begin{equation}
 \| {\mathbf A}  \|_{p,q} = \| {\mathbf b} \|_q = \left( \sum_{j = 1}^{n}\left( \sum_{i = 1}^{m} |a_{i,j}|^p \right)^{q/p}\right)^{1/q}
\end{equation}

Como se puede ver, esta definición engloba a la primera

\begin{equation}
 \| {\mathbf A}  \|_{p} = \| {\mathbf A}  \|_{p,p}
\end{equation}

##### Casos singulares

Probablemente, la norma matricial más conocida es la norma Frobenius, dada por

\begin{equation}
 \| {\mathbf A}  \|_{\text{Fro}} = \| {\mathbf A}  \|_{2} = \sqrt{\sum_{j = 1}^{n} \sum_{i = 1}^{m} |a_{i,j}|^2} = \sqrt{\operatorname{tr}({\mathbf A}^T {\mathbf A} )} = \sqrt{\sum_{i = 1}^{\min(m,n)} \sigma_i^2({\mathbf A} )}
\end{equation}

donde $\sigma_i({\mathbf A} )$ son los valores singulares de ${\mathbf A}$ (que se estudiarán en la siguiente sección)

Otra norma importante en aprendizaje automático es la norma $\ell_{2,1}$, dada por

\begin{equation}
 \| {\mathbf A}  \|_{2,1} = \sum_{j = 1}^{n}\left( \sum_{i = 1}^{m} |a_{i,j}|^2 \right)^{1/2}
\end{equation}

que no es más que la norma $\ell_1$ de las normas $\ell_2$ de cada columna

In [6]:
# Matriz de ejemplo
A = np.array([[2,1,3],[4,6,5],[7,8,9]])
a = A.reshape(9,1)

# Cálculo de la norma Frobenius
print(np.linalg.norm(A,ord='fro'))
print(np.linalg.norm(a,ord=2))

16.881943016134134
16.881943016134134


#### Normas matriciales inducidas por normas vectoriales

Dada la matriz ${\mathbf A}$ de dimensiones $m \times n$, la norma matricial inducida se define como

\begin{equation}
 \| {\mathbf A}  \|_{p,q} = \sup_{{\mathbf a}, {\mathbf a} \neq {\boldsymbol 0}} \frac{\| {\mathbf A}  {\mathbf a}\|_{p}}{\| {\mathbf a} \|_{q}} = \sup_{{\mathbf a}, \| {\mathbf a} \|_{q} = 1} \| {\mathbf A}  {\mathbf a}\|_{p} 
\end{equation}

donde $\sup$ es el supremo (máximo) de un conjunto. En el caso de $p = q$, la norma anterior se simplifica

\begin{equation}
 \| {\mathbf A}  \|_{p} = \| {\mathbf A}  \|_{p,p} = \sup_{{\mathbf a}, {\mathbf a} \neq {\boldsymbol 0}} \frac{\| {\mathbf A}  {\mathbf a}\|_{p}}{\| {\mathbf a} \|_{p}} = \sup_{{\mathbf a}, \| {\mathbf a} \|_{p} = 1} \| {\mathbf A}  {\mathbf a}\|_{p} 
\end{equation}

##### Casos singulares

Probablemente, la norma matricial inducida más conocida es la norma espectral, dada por

\begin{equation}
  \| {\mathbf A}  \|_{2} = \sup_{{\mathbf a}, \| {\mathbf a} \|_{2} = 1} \| {\mathbf A}  {\mathbf a}\|_{2} = \sqrt{\lambda_{max}({\mathbf A}^T {\mathbf A})} = \sigma_{max}({\mathbf A})
\end{equation}

donde $\lambda_{max}({\mathbf A}^T {\mathbf A})$ es el mayor autovalor de ${\mathbf A}^T {\mathbf A}$ (que se estudiará en la siguiente sección) y $\sigma_{max}({\mathbf A})$ es el mayor valor singular de ${\mathbf A}$ (que también se estudiará en la siguiente sección)

Otras dos normas importantes corresponden a los casos $p = 1$ y $p = \infty$, es decir,

\begin{equation}
 \| {\mathbf A}  \|_{1} = \max_{1 \leq j \leq n} \sum_{i=1}^{m} |a_{i,j}| \qquad \qquad \| {\mathbf A}  \|_{\infty} = \max_{1 \leq i \leq m} \sum_{j=1}^{n} |a_{i,j}|
\end{equation}